##GUARDAR TO-DO EN UNA CLASE class DeckValue

##EL METODO PARA CALCULAR Y VER EL VALOR DEL MAINDECK

def CalValorMain():
    pass #ALMACENAR LOS DATOS EN UN ARREGLO O LISTA Y SUMAR LOS PRECIOS DE TODAS LAS CARTAS Y TENER DE RETURN LA SUMA


##EL METODO PARA CALCULAR Y VER EL VALOR DEL EXTRADECK

def CalValorExtra():
    pass #ALMACENAR LOS DATOS EN UN ARREGLO O LISTA Y SUMAR LOS PRECIOS DE TODAS LAS CARTAS Y TENER DE RETURN LA SUMA


##EL METODO PARA CALCULAR Y VER EL VALOR DEL MAINDECK

def CalValorSide():
    pass #ALMACENAR LOS DATOS EN UN ARREGLO O LISTA Y SUMAR LOS PRECIOS DE TODAS LAS CARTAS Y TENER DE RETURN LA SUMA


## METODO QUE RECIBA COMO PARAMETRO LOS 3 RETURNS DE CADA DECK

def GetFullValue():
    pass