from storage import Storage
from element import Element

class StaticStorage(Storage):
    def __init__(self):
        self.elements = {
            "Hydrogen": Element("Hydrogen", "H", 1, 1.008, "no hay"),
            "Helium": Element("Helium", "He", 2, 4.003, "no hay"),
            "Lithium": Element("Lithium", "Li", 3, 6.941, "no hay"),
            "Beryllium": Element("Beryllium", "Be", 4, 9.012, "no hay"),
            "Boron": Element("Boron", "B", 5, 10.811, "no hay"),
            "Carbon": Element("Carbon", "C", 6, 12.011, "no hay"),
            "Nitrogen": Element("Nitrogen", "N", 7, 14.007, "no hay"),
            "Oxygen": Element("Oxygen", "O", 8, 15.999, "no hay"),
            "Fluorine": Element("Fluorine", "F", 9, 18.998, "no hay"),
            "Neon": Element("Neon", "Ne", 10, 20.180, "no hay"),
            "Sodium": Element("Sodium", "Na", 11, 22.990, "no hay"),
            "Magnesium": Element("Magnesium", "Mg", 12, 24.305, "no hay"),
            "Aluminum": Element("Aluminum", "Al", 13, 26.982, "no hay"),
            "Silicon": Element("Silicon", "Si", 14, 28.086, "no hay"),
            "Phosphorus": Element("Phosphorus", "P", 15, 30.974, "no hay"),
            "Sulfur": Element("Sulfur", "S", 16, 32.065, "no hay"),
            "Chlorine": Element("Chlorine", "Cl", 17, 35.453, "no hay"),
            "Argon": Element("Argon", "Ar", 18, 39.948, "no hay"),
            "Potassium": Element("Potassium", "K", 19, 39.098, "no hay"),
            "Calcium": Element("Calcium", "Ca", 20, 40.078, "no hay"),
            "Scandium": Element("Scandium", "Sc", 21, 44.956, "no hay"),
            "Titanium": Element("Titanium", "Ti", 22, 47.867, "no hay"),
            "Vanadium": Element("Vanadium", "V", 23, 50.942, "no hay"),
            "Chromium": Element("Chromium", "Cr", 24, 51.996, "no hay"),
            "Manganese": Element("Manganese", "Mn", 25, 54.938, "no hay"),
            "Iron": Element("Iron", "Fe", 26, 55.845, "no hay"),
            "Cobalt": Element("Cobalt", "Co", 27, 58.933, "no hay"),
            "Nickel": Element("Nickel", "Ni", 28, 58.693, "no hay"),
            "Copper": Element("Copper", "Cu", 29, 63.546, "no hay"),
            "Zinc": Element("Zinc", "Zn", 30, 65.390, "no hay"),
            "Gallium": Element("Gallium", "Ga", 31, 69.723, "no hay"),
            "Germanium": Element("Germanium", "Ge", 32, 72.640, "no hay"),
            "Arsenic": Element("Arsenic", "As", 33, 74.922, "no hay"),
            "Selenium": Element("Selenium", "Se", 34, 78.960, "no hay"),
            "Bromine": Element("Bromine", "Br", 35, 79.904, "no hay"),
            "Krypton": Element("Krypton", "Kr", 36, 83.800, "no hay"),
            "Rubidium": Element("Rubidium", "Rb", 37, 85.468, "no hay"),
            "Strontium": Element("Strontium", "Sr", 38, 87.620, "no hay"),
            "Yttrium": Element("Yttrium", "Y", 39, 88.906, "no hay"),
            "Zirconium": Element("Zirconium", "Zr", 40, 91.224, "no hay"),
            "Niobium": Element("Niobium", "Nb", 41, 92.906, "no hay"),
            "Molybdenum": Element("Molybdenum", "Mo", 42, 95.940, "no hay"),
            "Ruthenium": Element("Ruthenium", "Ru", 44, 101.070, "no hay"),
            "Rhodium": Element("Rhodium", "Rh", 45, 102.906, "no hay"),
            "Palladium": Element("Palladium", "Pd", 46, 106.420, "no hay"),
            "Silver": Element("Silver", "Ag", 47, 107.868, "no hay"),
            "Cadmium": Element("Cadmium", "Cd", 48, 112.411, "no hay"),
            "Indium": Element("Indium", "In", 49, 114.818, "no hay"),
            "Tin": Element("Tin", "Sn", 50, 118.710, "no hay"),
            "Antimony": Element("Antimony", "Sb", 51, 121.760, "no hay"),
            "Tellurium": Element("Tellurium", "Te", 52, 127.600, "no hay"),
            "Iodine": Element("Iodine", "I", 53, 126.905, "no hay"),
        }
    def search_element(self, name):
        if name in self.elements:
            return self.elements[name]
        return None
